name: CD

on:
  push:
    tags:
      - '*'

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.5.0-12.0.pre.94'
          channel: master
      - run: flutter pub get
      - run: flutter build apk